OUTPUT_DIR := $(PWD)/output
KERNEL_DIR := $(OUTPUT_DIR)/kernel
UBOOT_DIR := $(OUTPUT_DIR)/u-boot
INSTALL_DEV := /dev/null
ARCH := arm
TOOLCHAIN := DEB
CC := aarch64-linux-gnu-
CPUS := $(shell getconf _NPROCESSORS_ONLN)
PLATFORM := pico-imx6
